feat: добавляет квадратичный полином
shizand/statapp pull request #81
Opened 2023-10-16 14:33 UTC by Maks1mS

Closes #34.

2023-10-17 09:52 UTC, MisterMLiL commented on statapp/calculations.py
> +    print(data)
print - это зачем?

2023-10-17 10:26 UTC, Maks1mS commented on statapp/_vendor/multipolyfit.py
> +# pylint: skip-file
Нужно будет не забыть убрать

2023-10-20 09:16 UTC, MisterMLiL requested changes
Переделать RegressionResult и ExtendedRegressionResult

2023-10-20 10:26 UTC, MisterMLiL approved these changes

2023-10-20 10:26 UTC, merged